[project]
name = "tql"
version = "0.0.0"
requires-python = ">=3.11,<3.12"
dependencies = [
  "absl-py",
  "augmax>=0.3.4",
  "chex",
  "Cython==0.29.34",
  "distrax",
  "dm_env_wrappers",
  "easydict",
  "flax==0.10.2",
  "gym==0.23.1",
  "gymnasium==0.29.1",
  "h5py",
  "jax-jumpy==1.0.0",
  "jupyter",
  "matplotlib",
  "ml_collections==1.0.0",
  "moviepy",
  "numpy",
  "ogbench==1.1.0",
  "optax>=0.2.0,<0.3",
  "openpi",
  "openpi-client",
  "orbax-checkpoint==0.11.13",
  "pip==22.2.2",
  "scikit-learn",
  "scipy",
  "seaborn",
  "shimmy[gym-v21,gym-v26]",
  "submitit",
  "tensorboardX",
  "tensorflow-probability==0.19.0",
  "tqdm",
  "websockets~=13.1",
  "wandb",
  "wandb_osh",
  "d4rl @ git+https://github.com/Farama-Foundation/D4RL.git@2b96431a0e9fd90c8032624b0dc3cd4514d15632",
  "robomimic @ git+https://github.com/ARISE-Initiative/robomimic@dde3a6e74886e0768cedf18f8f9c813d47d31ebd",
  "robosuite @ git+https://github.com/ARISE-Initiative/robosuite@de64fa5935f9f30ce01b36a3ef1a3242060b9cdb",
  "transformers==4.53.2",
  "patchelf>=0.17.2.4",
  "tyro>=1.0.4",
  "ipdb>=0.13.13",
  "pandas>=2.0.3",
  "pyarrow>=17.0.0",
  "jax[cuda12]==0.5.3",
  "scipy<1.13",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["agents", "utils", "envs"]

[tool.uv]
override-dependencies = [
  "mujoco==3.2.3",
  "ml-dtypes==0.4.1",
  "tensorstore==0.1.74",
  "datasets>=3.0,<4.0",
]
environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]
find-links = ["https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"]

[tool.uv.sources]
openpi = { path = "../expo-ft/expo_ft/agents/vla/openpi", editable = true }
openpi-client = { path = "../expo-ft/expo_ft/agents/vla/openpi/packages/openpi-client", editable = true }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
