#!/bin/bash
set -euo pipefail
cd /iris/u/ronpo/projects/new_mtql

LAUNCHER=drawer_task/train.sh
PROJECT=offline-drawer-task-v1

sbatch --partition=iris --export=ALL,WANDB_PROJECT="$PROJECT",RUN_KIND=rl,SETTING_ID=rl_h16_s125_a300,HIST_LENGTH=16,HIST_STRIDE=125,ALPHA=300,DISCOUNT=0.999,NORM_Q=true "$LAUNCHER"
sbatch --partition=iris --export=ALL,WANDB_PROJECT="$PROJECT",RUN_KIND=rl,SETTING_ID=rl_h20_s80_a300,HIST_LENGTH=20,HIST_STRIDE=80,ALPHA=300,DISCOUNT=0.999,NORM_Q=true "$LAUNCHER"
sbatch --partition=iris --export=ALL,WANDB_PROJECT="$PROJECT",RUN_KIND=rl,SETTING_ID=rl_h20_s90_a300,HIST_LENGTH=20,HIST_STRIDE=90,ALPHA=300,DISCOUNT=0.999,NORM_Q=true "$LAUNCHER"
sbatch --partition=iris --export=ALL,WANDB_PROJECT="$PROJECT",RUN_KIND=rl,SETTING_ID=rl_h20_s100_a100,HIST_LENGTH=20,HIST_STRIDE=100,ALPHA=100,DISCOUNT=0.999,NORM_Q=true "$LAUNCHER"
sbatch --partition=iris --export=ALL,WANDB_PROJECT="$PROJECT",RUN_KIND=rl,SETTING_ID=rl_h20_s100_a500,HIST_LENGTH=20,HIST_STRIDE=100,ALPHA=500,DISCOUNT=0.999,NORM_Q=true "$LAUNCHER"
sbatch --partition=iris --export=ALL,WANDB_PROJECT="$PROJECT",RUN_KIND=rl,SETTING_ID=rl_h20_s100_g9995,HIST_LENGTH=20,HIST_STRIDE=100,ALPHA=300,DISCOUNT=0.9995,NORM_Q=true "$LAUNCHER"
sbatch --partition=iris --export=ALL,WANDB_PROJECT="$PROJECT",RUN_KIND=rl,SETTING_ID=rl_h20_s100_nonorm,HIST_LENGTH=20,HIST_STRIDE=100,ALPHA=300,DISCOUNT=0.999,NORM_Q=false "$LAUNCHER"
sbatch --partition=iris --export=ALL,WANDB_PROJECT="$PROJECT",RUN_KIND=rl,SETTING_ID=rl_h24_s80_a100,HIST_LENGTH=24,HIST_STRIDE=80,ALPHA=100,DISCOUNT=0.999,NORM_Q=true "$LAUNCHER"
sbatch --partition=iris --export=ALL,WANDB_PROJECT="$PROJECT",RUN_KIND=rl,SETTING_ID=rl_h24_s80_a500,HIST_LENGTH=24,HIST_STRIDE=80,ALPHA=500,DISCOUNT=0.999,NORM_Q=true "$LAUNCHER"
sbatch --partition=iris --export=ALL,WANDB_PROJECT="$PROJECT",RUN_KIND=rl,SETTING_ID=rl_h32_s64_a500,HIST_LENGTH=32,HIST_STRIDE=64,ALPHA=500,DISCOUNT=0.999,NORM_Q=true "$LAUNCHER"
